name: Docker build and deploy
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - 'master'
      - 'develop'
      - 'test'

jobs:
  docker-build-prod:
    if: github.ref == 'refs/heads/master'
    uses: InnoStudyHub/back-end/.github/workflows/build_docker_image.yaml@master
    with:
      tag: latest
      environment: prod
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

  docker-build-dev:
    if: github.ref == 'refs/heads/develop'
    uses: InnoStudyHub/back-end/.github/workflows/build_docker_image.yaml@develop
    with:
      tag: dev_latest
      environment: dev
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    needs: [docker-build-dev]
    uses: InnoStudyHub/back-end/.github/workflows/deploy_template.yaml@develop
    with:
      tag: dev_latest
      environment: dev
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      ENVFILE: ${{ secrets.ENVFILE }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    needs: [ docker-build-prod ]
    uses: InnoStudyHub/back-end/.github/workflows/deploy_template.yaml@master
    with:
      tag: latest
      environment: prod
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST_PROD }}
      ENVFILE: ${{ secrets.ENVFILE_DEV }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME_PROD }}
